---
- name: Install app dependencies and run app with PM2
  hosts: web
  gather_facts: yes
  become: yes

  tasks:
    - name: Install required system packages
      ansible.builtin.apt:
        name:
          - curl
          - git
        state: present
        update_cache: yes

    - name: Install Node.js 20 and npm
      ansible.builtin.shell: |
        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        apt-get install -y nodejs
      args:
        executable: /bin/bash

    - name: Install PM2 globally
      community.general.npm:
        name: pm2
        global: yes

    - name: Ensure PM2 directory exists for ubuntu user
      ansible.builtin.file:
        path: /home/ubuntu/.pm2
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Clone the app repository from GitHub
      ansible.builtin.git:
        repo: "https://github.com/marmari9/tech501-sparta-app.git"
        dest: /home/ubuntu/app
        version: main
        force: yes

    - name: Install app dependencies
      ansible.builtin.command:
        cmd: npm install
        chdir: /home/ubuntu/app

    - name: Set DB_HOST environment variable (Permanent)
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: 'DB_HOST=mongodb://172.31.55.4:27017/posts'
        create: yes

    - name: Reload system-wide environment variables
      ansible.builtin.shell: "export $(cat /etc/environment | xargs)"
      args:
        executable: /bin/bash
    - name: Seed the database automatically
      ansible.builtin.shell: "node seeds/seed.js"
      args:
        chdir: /home/ubuntu/app
      become_user: ubuntu

    - name: Start the app with PM2
      ansible.builtin.shell: |
        pm2 delete tech501-sparta-app || true
        pm2 start npm --name tech501-sparta-app -- start
        pm2 save
      args:
        chdir: /home/ubuntu/app
      become_user: ubuntu

    - name: Enable PM2 on system startup
      ansible.builtin.shell: |
        env PATH=$PATH:/usr/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
      args:
        executable: /bin/bash
      become: yes

    - name: Allow traffic on port 3000
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 3000
        jump: ACCEPT
