---
- name: Update and Upgrade Packages on Web and DB
  hosts: web, db
  become: yes
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: full

    - name: Autoremove unnecessary packages
      ansible.builtin.apt:
        autoremove: yes

